import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { Box } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex ">
          <div>
            <Sidebar/>
          </div>
          <Box sx={{
    display: 'flex',
    flexDirection: 'column',
    width: '100%', // This is equivalent to w-full
    padding: '80px', // This is equivalent to p-[80px]
    paddingLeft: '50px', // This is equivalent to pl-[50px]
    
  }}>
           
            {children}
          </Box>
        </div>
        
        
        </body>
    </html>
  );
}
